name: Back End CI/CD

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 22.14
        uses: actions/setup-node@v3
        with:
          node-version: '22.14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build
        if: github.ref == 'refs/heads/main'
        run: npm run build

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}